import { ClientProvider } from "./(components)/components";
import "../styles/globals.css";
import Head from "./head";
import { Metadata } from "next";
import { AuthContextProvider } from "./authContext";

export const metadata: Metadata = {
  title: "WriteBrain",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <Head />
      <body>
        <AuthContextProvider>
            {/* <AuthRouter> */}
              <ClientProvider />
              {/* {pageLoading ?
                <div className=''>Loading...</div> 
                : 
                <main>{children}</main>
              } */}
              <main>{children}</main>
            {/* </AuthRouter> */}
          </AuthContextProvider>
      </body>
    </html>
  );
}