name: Release

on:
  push:
    branches: [main, beta, feature-branch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npx ci
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git      
    # - name: Lint
    #   run: npm run lint-fix
    # - name: Test
    #   run: npm run test:unit --if-present
    - name: Build
      env:
        NEXT_PUBLIC_FIREBASE_CONFIG_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_CONFIG_API_KEY}}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:  ${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID : ${{secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}
      run: npm run build      
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release